import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import "@/styles/global.scss";
import { Roboto, Nunito, Oswald } from "next/font/google";

const roboto = Roboto({
    subsets: ["cyrillic"],
    weight: ["400", "700"],
    variable: "--font-roboto",
});

const nunito = Nunito({
    subsets: ["cyrillic"],
    weight: ["400", "700"],
    variable: "--font-nunito",
});

const oswald = Oswald({
    subsets: ["cyrillic"],
    weight: ["400", "700"],
    variable: "--font-oswald",
});

export const metadata = {
    title: "Музей памʼяті митрополита Андрея",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="uk">
            <body
                className={`${roboto.variable} ${nunito.variable} ${oswald.variable}`}
            >
                <Header />
                <main className="container main">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
