import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import "@/styles/global.scss";
import { Roboto } from "next/font/google";

const roboto = Roboto({
    subsets: ["cyrillic"],
    weight: ["400", "700"],
    variable: "--font-roboto",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="uk">
            <body className={roboto.className}>
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
